### ISSUE TITLE
setState() method that automatically emits

### ISSUE THREAD

**Issue by nikrowell** [estrattonbailey/picostate#3]
Promise I'm not going to bombard you with Issues and PRs 😆

One more pattern I've found myself using with picoapp + picostate is defining a `setState` function that automatically emits change notifications:

```javascript
const store = createStore({
  isLoading: false,
  foo: true,
  bar: false
})

function setState(fn) {
  const dispatch = store.hydrate(fn)
  dispatch()
}

function onSubmit(event) {
  event.preventDefault()
  setState({isLoading: true})
  // ...
}
```

I've found that I almost always want to emit after hydrating state. This feels slightly more clear than `store.hydrate(fn)()` and is a nice familiar function name 😀

Interesting?

**Comment by estrattonbailey** [comment]
Haha all good! Love to see it.

This is fair, and would only add a few bytes to the size, so I have no problem with it. Wanna PR?

**Comment by nikrowell** [comment]
On second thought, maybe it's an unnecessary addition. I have no problem continuing to define a separate `setState` helper, and may end up doing something like this anyways:
```javascript 
const store = createStore({...});
const setState = store.setState;
```
Let's keep the bytes out unless you'd prefer to have it in there...
